[package]
name = "bin"
version = "0.1.0"
authors = ["Gunwant Jain <mail@wantguns.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
rocket = "0.4.6"
