[package]
name = "bin"
version = "0.1.0"
authors = ["Gunwant Jain <mail@wantguns.dev>"]
edition = "2018"

[dependencies]
rand = "0.8.0"
rocket = "0.4.6"
rocket_contrib = { version = "0.4.6", features = ["tera_templates"] }
tree_magic = "0.2.3"

